package driver

import (
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"slices"
	"strings"
)

var errGenerated = errors.New("linters.exclusions.generated is not a text")

// laxMarkers are the texts the lax mode of golangci-lint finds in the comments
// of a generated file, in lower case (exclusion_generated_file_matcher.go).
var laxMarkers = []string{
	"code generated",
	"do not edit",
	"autogenerated file",
	"* generated by: swagger codegen ",
}

// Generated is which files a finding in is dropped, as
// linters.exclusions.generated of a golangci-lint configuration says: those
// that follow the Go convention for generated code, those whose comments say
// they are generated, or none.
type Generated string

const (
	GeneratedStrict  Generated = "strict"
	GeneratedLax     Generated = "lax"
	GeneratedDisable Generated = "disable"
)

// generatedOf reads linters.exclusions.generated of golangci, a golangci-lint
// configuration, as golangci-lint does: weakly typed, strict when the key is
// left empty or out, as it is of the command's own file, nil here, and lax for
// any other text but disable, since golangci-lint compares the mode only with
// strict and disable.
func generatedOf(golangci map[string]any) (Generated, error) {
	linters, _ := golangci["linters"].(map[string]any)
	exclusions, _ := linters["exclusions"].(map[string]any)
	value := exclusions["generated"]
	if empty, isMap := value.(map[string]any); value == nil || isMap && len(empty) == 0 {
		return GeneratedStrict, nil
	}
	mode, isText := text(value)
	if !isText {
		return "", errGenerated
	}
	switch Generated(mode) {
	case "", GeneratedStrict:
		return GeneratedStrict, nil
	case GeneratedDisable:
		return GeneratedDisable, nil
	}
	return GeneratedLax, nil
}

// kept is found but the findings in the files g says are generated, each
// file read once, whatever the number of findings in it.
func (g Generated) kept(found []finding) ([]finding, error) {
	if g == GeneratedDisable {
		return found, nil
	}
	generated := make(map[string]bool)
	var kept []finding
	for _, current := range found {
		path := current.position.Filename
		if _, known := generated[path]; !known {
			is, err := g.generated(path)
			if err != nil {
				return nil, err
			}
			generated[path] = is
		}
		if !generated[path] {
			kept = append(kept, current)
		}
	}
	return kept, nil
}

// generated reports whether the file at path is generated, as golangci-lint's
// matcher reads it: up to the package clause, and, in strict mode, by the Go
// convention alone.
func (g Generated) generated(path string) (bool, error) {
	file, err := parser.ParseFile(
		token.NewFileSet(),
		path,
		nil,
		parser.PackageClauseOnly|parser.ParseComments,
	)
	if err != nil {
		return false, fmt.Errorf("%s: %w", path, err)
	}
	if g == GeneratedStrict {
		return ast.IsGenerated(file), nil
	}
	comments := make([]string, 0, len(file.Comments))
	for _, group := range file.Comments {
		comments = append(comments, strings.TrimSpace(group.Text()))
	}
	joined := strings.ToLower(strings.Join(comments, "\n"))
	return slices.ContainsFunc(laxMarkers, func(marker string) bool {
		return strings.Contains(joined, marker)
	}), nil
}
